apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
data:
  client-id: {{ .Values.vault.authentik.clientId | b64enc | quote }}
  client-secret: {{ .Values.vault.authentik.clientSecret | b64enc | quote }}

