apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "grafana-role"
        vault.hashicorp.com/agent-inject-secret-AUTHENTIK_CLIENT_ID: "secret/authentik"
        vault.hashicorp.com/agent-inject-secret-AUTHENTIK_CLIENT_SECRET: "secret/authentik"
        vault.hashicorp.com/agent-inject-template-AUTHENTIK_CLIENT_ID: |
          {{- with secret "secret/authentik" -}}
          {{ .Data.data.client-id }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-AUTHENTIK_CLIENT_SECRET: |
          {{- with secret "secret/authentik" -}}
          {{ .Data.data.client-secret }}
          {{- end }}
    spec:
      serviceAccountName: grafana  # Ensure this service account exists and is bound to Vault role
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "Authentik"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vault-injected
                  key: AUTHENTIK_CLIENT_ID
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vault-injected
                  key: AUTHENTIK_CLIENT_SECRET
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              value: "http://192.168.0.208:9000/application/o/authorize/"
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              value: "http://192.168.0.208:9000/application/o/token/"
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              value: "http://192.168.0.208:9000/application/o/userinfo/"
            - name: GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH
              value: "username"
            - name: GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH
              value: "name"
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
              value: "groups"
            - name: GF_SERVER_ROOT_URL
              value: "http://192.168.0.204"

