apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "grafana-role"
        vault.hashicorp.com/agent-inject-secret-client-id: "secret/authentik"
        vault.hashicorp.com/agent-inject-secret-client-secret: "secret/authentik"
    spec:
      serviceAccountName: grafana  # Ensure this service account exists and is bound to Vault role
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: "Authentik"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: client-id
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: client-secret
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_AUTH_URL
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_TOKEN_URL
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_API_URL
            - name: GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_LOGIN_ATTRIBUTE_PATH
            - name: GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_NAME_ATTRIBUTE_PATH
            - name: GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_ROLE_ATTRIBUTE_PATH
            - name: GF_SERVER_ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: SERVER_ROOT_URL
            - name: GF_AUTH_SIGNOUT_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: OAUTH_SIGNOUT_REDIRECT_URL

