apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-vault-role-binding
  namespace: default  # Adjust to your namespace
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: default  # Adjust to your namespace
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io
